/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A product from Acme's catalog
 */
export interface Product {
  /**
   * The unique identifier for a product
   */
  id: number;
  /**
   * Name of the product
   */
  name: string;
  price: number;
  tags?: [string, ...string[]];
  [k: string]: unknown;
}
